# Generated by Django 3.2 on 2021-04-09 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('draft', 'Отложено'), ('done', 'Выполнено')], default='draft', max_length=10, verbose_name='Состояние')),
                ('important', models.BooleanField(default=False, verbose_name='Важно')),
                ('public', models.BooleanField(default=False, verbose_name='Публично')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 4, 10, 15, 55, 14, 645839, tzinfo=utc), verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
