# Generated by Django 3.2 on 2021-04-09 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 18, 6, 39, 161036, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
